version: "3"
services:
  uploader:
    build:
      context: .
      dockerfile: uploader.dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=filedb
  generator:
    build:
      context: .
      dockerfile: generator.dockerfile
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=filedb
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=filedb
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

networks:
  default:
    external:
      name: my_network
